### ISSUE TITLE
Sending custom dimensions / metrics

### ISSUE THREAD

**Issue by gradosevic** [theiconic/php-ga-measurement-protocol#14]
Any example how to send custom dimensions and metrics? I tried sending but nothing was sent to the GA. Is there any pre-setup that has to be done before sending the data? Thanks!

**Comment by yanict** [comment]
Hi,
I actually face to a similar problem. I'm trying to pass a string as value but i et an error :
`When setting parameter TheIconic\Tracking\GoogleAnalytics\Parameters\CustomDimensionsMetrics\CustomDimension a numeric index between 1 - 200 must be passed for the second argument `

This is due to the Indexable trait set on the CustomDimension and CustomMetric classes.
That looks like an error in my point of view...

@gradosevic, did you finally managed to send customs datas ?

thanks for your help

**Comment by gradosevic** [comment]
I still have no luck sending custom data

**Comment by YaniceSocialCar** [comment]
ok thanks.
let's wait for an answer from developers for the moment.

**Comment by yanict** [comment]
ok thanks.
let's wait for an answer from developers for the moment.

**Comment by gradosevic** [comment]
In order to send custom data it's necessary to set them up correctly in GA. I have created a wrapper for this library [gradosevic/easy-ga](https://github.com/gradosevic/easy-ga) that can be used for sending custom data. Please check Readme for tutorial how to achieve that.
