### ISSUE TITLE
Problems with addProductImpression

### ISSUE THREAD

**Issue by khalwat** [theiconic/php-ga-measurement-protocol#26]
Thanks for the library, I love it!  I'm in the middle of adding some Google Enhanced Ecommerce tracking, and as part of that, I'm trying to add a ProductImpression to the Analytics object:

```
            $productData = [
                'sku' => $productVariant->sku,
                'name' => $productVariant->title,
                'price' => number_format($productVariant->price, 2, '.', '')
            ];
            $analytics->addProductImpression($productData);
```

But I get the error:

```
When setting parameter TheIconic\Tracking\GoogleAnalytics\Parameters\EnhancedEcommerce\ProductImpressionCollection a numeric index between 1 - 200 must be passed for the second argument
```

If I change it to `$analytics->addProduct($productData);` then it works fine, which is odd.

The backtrace looks like this:

![google chromescreensnapz079](https://cloud.githubusercontent.com/assets/7570798/17957143/480982b8-6a5d-11e6-9c19-a7f05937cffa.png)

Any ideas?

**Comment by jorgeborges** [comment]
hey @khalwat, for products impressions you have to pass a second argument that represents the List Index (because in the same page you can have several lists, such as main catalog and recommendations)

`setProductImpressionListName($value, $index)`
`addProductImpression(array $productData, $index)`

You can read more about it in the official docs:
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#il_nm

So if you only have one list of products, you can fix this by doing
```
$productData = [
    'sku' => $productVariant->sku,
    'name' => $productVariant->title,
    'price' => number_format($productVariant->price, 2, '.', '')
];

$analytics->addProductImpression($productData, 1);
```
Cheers.

**Comment by khalwat** [comment]
Ah, thank you, my bad.  This I believe is an actual bug (or at least an omission):

`addProductImpression` takes an `impressionFieldObject` rather than a `productFieldObject`, and a valid parameter for this is: `'list'`:

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#il_nm

However in `ProductImpression.php`, the `'list'` parameter isn't in the allowed parameters:

    protected $parameterNameMapper = [
        '/^sku$/' => 'id',
        '/^name$/' => 'nm',
        '/^brand$/' => 'br',
        '/^category$/' => 'ca',
        '/^variant$/' => 'va',
        '/^price$/' => 'pr',
        '/^position$/' => 'ps',
        '/^custom_dimension_(\d{1,3})$/' => 'cd',
        '/^custom_metric_(\d{1,3})$/' => 'cm',
    ];

...which make you unable to associate an impression with the `list` it is shown in.

**Comment by jorgeborges** [comment]
its is missing! I'll fix it this weekend and releasing a new minor version.

**Comment by khalwat** [comment]
Great, thank you!  Then I'll be able to enable my Product Impressions code :)

**Comment by khalwat** [comment]
I will be around all weekend if you want someone to test it for you.  lmk!

**Comment by khalwat** [comment]
I think (?) but I'm not really sure that this should be a compound parameter like:

    protected $name = 'il:i:nm';

?

**Comment by khalwat** [comment]
Hey @jorgeborges I just wanted to see if there was any movement on this.  I'd be happy to do it myself, and give you a pull request, I just need a little guidance.

**Comment by khalwat** [comment]
Just wanted to see if this was still on the radar @jorgeborges ?  I'd be happy to assist if I had a little input re: how to structure things.

**Comment by jorgeborges** [comment]
@khalwat sorry for taking so long to reply, I've been away because of work plus personal reasons...

Anyway, on a closer inspection to this, I don't think that field belongs to the Product Impression per se.

Look at the documentation
![screenshot 2016-10-14 11 10 57](https://cloud.githubusercontent.com/assets/1531431/19373674/b6f73c70-9211-11e6-945a-d69be02ae686.png)

The name of the impression list is supposed to set separately from the products, so in order to send some impressions from, say, two (2) different lists, you would do something like this:

```php
// Adding to the first list
$analytics->setProductImpressionListName('Main Catalog', 1);

$productData = [
    'sku' => 'AAAA-5555',
    'name' => 'Test Product',
    'brand' => 'Test Brand',
    'category' => 'Test Category 1/Test Category 2',
    'variant' => 'blue',
    'price' => 85.00,
    'position' => 4
];

$analytics->addProductImpression($productData, 1);

// Adding to a second list
$analytics->setProductImpressionListName('Recommendations', 2);

$productData2 = [
    'sku' => 'AAAA-6666',
    'name' => 'Test Product',
    'brand' => 'Test Brand',
    'category' => 'Test Category 1/Test Category 2',
    'variant' => 'yellow',
    'price' => 85.00,
    'position' => 1
];

$analytics->addProductImpression($productData2, 2);
```

There is no parameter `list` for product impressions, the index of the impression list is added in the parameter name for you, that's why you pass the index number when adding them.

Is this clear?

**Comment by khalwat** [comment]
That is clear; sorry for my misunderstanding. I'm implementing these changes now.
