### ISSUE TITLE
Why ClientId is required ?!

### ISSUE THREAD

**Issue by matiazar** [theiconic/php-ga-measurement-protocol#45]
Hi. Why ClientId is required for a pageview event?!

**Comment by jorgeborges** [comment]
As per the documentation provided by Google Analytics, you must provided either Client ID or User ID in every hit you send. https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid

**Comment by matiazar** [comment]
thanks @jorgeborges for answer me.

and how do you pass a Client ID to the php library ? where I can find it? on what cookie?!
thanks in advance 4 all !!

**Comment by jorgeborges** [comment]
@matiazar Read the "Usage" section on the README. It explains how to send the Client ID, as per how to get the Client Id from the Cookie: https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#getting_the_client_id_from_the_cookie

**Comment by matiazar** [comment]
@jorgeborges  thanks again.
I have read it before... Sorry for my ignorance.
But I can read the Client Id on javascript (client)

ga(function(tracker) {
  var clientId = tracker.get('clientId');
});

What the best way to read it, send it to php and store it for future usages?!
Thanks again.

**Comment by matiazar** [comment]
@jorgeborges can you help me with this?!
thanks!

**Comment by jorgeborges** [comment]
@matiazar You have several options, you would need the Javascript to set the Client ID in POST field, or you can send it over the HTTP headers too.

Then, PHP provides functions to read cookie data, also if you are using a framework its likely it provides an easier to use abstraction to get cookie data, check their documentation. As to where to store them (I assume you mean server side), you have several options like sessions or a database, or just send it every time instead of storing it, that way to avoid state.

Sorry for not providing you with a more complete solution. This is actually a big architectural/design question that goes out of the scope of this library. Good luck.
